
ocr_prompt="""
Transcribe this image with Slovak text into plain Slovak text. Keep the formatting. 
Return only the Slovak text without annotations.Ignore handwritten notes.
"""
book_prefix="Kniha"

page_prefix="_Strana"

pdf_background = "./data/bg_textur.jpg"

doc_template = "./data/template.docx"